conversation/urls.py
from django.urls import path
from .views import conversation_view
from . import views
app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('', conversation_view, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),  # Default path for the inbox view
    path('new/<int:item_pk>/', conversation_view, name='new'),  # Path to create a new conversation
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import user_logout

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    path('logout/', user_logout, name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from .import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT )

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


    

core/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    
    # show listed items on site
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

def user_logout(request):
    logout(request)
    return redirect('core:index')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.2/main.min.css" rel="stylesheet" />
    
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.2/main.min.js"></script>
    <title>{% block title %} {% endblock %} | Marketplace </title>
</head>
<body>
    <nav class="py-4 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-2xl font-semibold text-teal-600 hover:text-teal-800">Marketplace</a>

        <div class="flex space-x-4">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold text-gray-800 hover:text-teal-500">New Item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold text-gray-800 hover:text-teal-500">Browse</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}" class="px-4 py-2 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-600">Inbox</a>
            <a href="{% url 'dashboard:index' %}" class="px-4 py-2 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-600">Dashboard</a>
            <a href="{% url 'core:logout' %}" class="px-4 py-2 text-lg font-semibold bg-red-500 text-white rounded-lg hover:bg-red-600">Logout</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-4 py-2 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-600">Sign Up</a>
                <a href="{% url 'core:login' %}" class="px-4 py-2 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-600">Login</a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 bg-gray-800 text-gray-300">
        <div class="container mx-auto flex justify-between">
            <div class="w-2/3 pr-10">
                <h3 class="mb-4 text-xl font-semibold text-gray-400">About</h3>
                <p class="text-lg">Welcome to the best Marketplace on the internet</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-4 text-xl font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms Of Use</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %} | 

{% block content %}
    <h1>Contact Page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2> 
       
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div class="flex flex-col bg-white rounded-xl shadow-md overflow-hidden">
                    <a href="{% url 'item:detail' pk=item.id %}" class="flex flex-col h-full">
                        <div class="flex-shrink-0">
                            <img src="{{ item.image.url }}" class="w-full h-48 object-cover">
                        </div>
                        <div class="flex-1 p-6 flex flex-col">
                            <h2 class="text-2xl mb-2">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: £{{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
       </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <div class="max-w-2xl mx-auto">
            <form method="get" action="{% url 'item:items' %}" class="flex flex-col items-center">
                <input name="query" class="w-full py-4 px-6 border rounded-xl mb-4" type="text" value="{{ query }}" placeholder="Find the perfect item right here...">
                <button class="py-3 px-6 text-lg bg-teal-500 text-white rounded-xl hover:bg-teal-700">Search</button>
            </form>
        </div>

        <div class="mt-12">
            <p class="font-semibold text-center mb-4">Categories</p>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                {% for category in categories %}
                    <div class="bg-white rounded-xl shadow-md p-4">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}" class="text-lg font-semibold block text-center hover:text-teal-500">
                            {{ category.name }}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        
    </div>
{% endblock %}

core/templates/core/item_detail.html
{% extends 'core/base.html' %}

{% block title %}Item Description{% endblock %}

{% block content %}
    <h1>{{ item.name }}</h1>
    <p>{{ item.description }}</p>
    <p>Daily Price: £{{ item.daily_price }}</p>
    
    <p>Available Dates:</p>
    <ul>
        {% for date in available_dates %}
            <li>{{ date }}</li>
        {% endfor %}
    </ul>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl p-4">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg text-white bg-teal-500 hover:bg-teal-700 rounded-xl">Login</button>
    </form>

</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl p-4">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg text-white bg-teal-500 hover:bg-teal-700 rounded-xl">Submit</button>
    </form>

</div>
{% endblock %}